[tox]
envlist = lint

[testenv]
allowlist_externals = 
    tox

[testenv:lint]
description = Run all code linters
skip_install = true
deps =
commands =
    tox -e pylint,check-format

[testenv:pylint]
description = Run Python code linters
skip_install = true
deps =
    flake8
commands =
    flake8 claudebox/

[testenv:check-format]
description = Check all code formatting
skip_install = true
deps =
commands =
    tox -e check-pyformat

[testenv:check-pyformat]
description = Check Python code formatting
skip_install = true
deps =
    black
    isort
commands =
    black --check claudebox/
    isort --check-only claudebox/

[testenv:format]
description = Apply code formatting
skip_install = true
deps =
    black
    isort
commands =
    black claudebox/
    isort claudebox/

[testenv:unit-tests]
description = Run unit tests with coverage
deps =
    pytest
    pytest-cov
commands =
    python -m pytest tests/tests/unit/ -v --cov=selcraft --cov-report=term --cov-report=xml

[testenv:integration-tests]
sitepackages=True
description = Run integration tests with coverage
deps =
    pytest
    pytest-cov
commands =
    python -m pytest tests/tests/integration/ -v --cov=selcraft --cov-report=term --cov-report=xml

[flake8]
# Line break before operator is current best practice
# W503  line break before binary operator
max-line-length = 120
ignore = W503, E704

[isort]
profile = black
line_length = 120 