ARG fedora_version=latest
ARG CLAUDE_CODE_VERSION=latest

FROM quay.io/fedora/fedora:${fedora_version}

# Install Claude and other, helpful tools
RUN dnf upgrade -y && \
    dnf install \
        git \
        jq \
        npm \
        procps-ng \
        systemd \
        tree \
        -y
RUN npm install -g @anthropic-ai/claude-code@${CLAUDE_CODE_VERSION}

# Create claude user
RUN groupadd -r claude && useradd -r -g claude claude
RUN mkdir -p /home/claude
RUN chown -R claude:claude /home/claude

# Copy .bashrc containing variable exports for claude
COPY files/.bashrc /home/claude/.bashrc

# Create mounted OCI artifacts directories
RUN mkdir -p /var/oci-artifacts/skills
RUN mkdir -p /var/oci-artifacts/agents

# Create skills directory for claude
RUN mkdir -p /home/claude/.claude/skills
# Setup unpack-skills service
COPY files/systemd/unpack-skills.sh /usr/local/bin/unpack-skills.sh
COPY files/systemd/unpack-skills.service /etc/systemd/system/unpack-skills.service
RUN mkdir -p /etc/systemd/system/multi-user.target.wants && \
ln -s /etc/systemd/system/unpack-skills.service /etc/systemd/system/multi-user.target.wants/unpack-skills.service

# Create agents directory for claude
RUN mkdir -p /home/claude/.claude/agents
# Setup unpack-agents service
COPY files/systemd/unpack-agents.sh /usr/local/bin/unpack-agents.sh
COPY files/systemd/unpack-agents.service /etc/systemd/system/unpack-agents.service
RUN mkdir -p /etc/systemd/system/multi-user.target.wants && \
ln -s /etc/systemd/system/unpack-agents.service /etc/systemd/system/multi-user.target.wants/unpack-agents.service
