ARG fedora_version=latest
ARG CLAUDE_CODE_VERSION=latest

FROM quay.io/fedora/fedora:${fedora_version}

# Install Claude
RUN dnf upgrade -y && \
    dnf install npm tree -y
RUN npm install -g @anthropic-ai/claude-code@${CLAUDE_CODE_VERSION}

# Copy .bashrc containing variable exports for claude
COPY containers/files/.bashrc /root/.bashrc

# Create skills directory for claude
RUN mkdir -p /root/.claude/skills

# Setup unpack-skills service
COPY containers/files/systemd/unpack-skills.sh /usr/local/bin/unpack-skills.sh
COPY containers/files/systemd/unpack-skills.service /etc/systemd/system/unpack-skills.service
RUN ln -s /etc/systemd/system/unpack-skills.service /etc/systemd/system/multi-user.target.wants/unpack-skills.service
