#!/bin/bash

MOUNT_DIR="${1}"
if [ -z "${MOUNT_DIR}" ]; then
    CURR_DIR=$(pwd)
    MOUNT_DIR="${CURR_DIR}"
fi
NAME=$(basename "${MOUNT_DIR}")
CONTAINER_NAME=claude-box-"${NAME}"

stop_container() {
    podman stop "${CONTAINER_NAME}" &> /dev/null
}

# Ensure container cleanup after exiting container
trap stop_container EXIT INT TERM

podman run -d \
    --security-opt label=disable \
    --rm \
    --name "${CONTAINER_NAME}" \
    -v ~/.config/gcloud/:/root/.config/gcloud \
    -v "${MOUNT_DIR}":/workspace \
    --mount=type=artifact,src=quay.io/rhivos-skills/xlsx:latest,dst=/var/oci-artifacts/skills/xlsx \
    --mount=type=artifact,src=quay.io/rhivos-skills/docx:latest,dst=/var/oci-artifacts/skills/docx \
    quay.io/rhivos-ai-tools/claude-box:latest /sbin/init

podman exec -it -w /workspace "${CONTAINER_NAME}" /bin/bash
