#!/bin/bash

SCRIPT_DIR=$(dirname "$(readlink -f "$0")")
ROOT_DIR="${SCRIPT_DIR}"/..
SUBMODULES_DIR="${ROOT_DIR}"/submodules

SKILLS_DIR="${ROOT_DIR}"/skills
ANTHROPIC_SKILLS_REPO="anthropic"
ANTHROPIC_SKILLS_DIR="${SKILLS_DIR}"/"${ANTHROPIC_SKILLS_REPO}"
OBRA_SKILLS_REPO="obra"
OBRA_SKILLS_DIR="${SKILLS_DIR}"/"${OBRA_SKILLS_REPO}"

AGENT_DIR="${ROOT_DIR}"/agents
AGENCY_AGENT_REPO="agency"
AGENCY_AGENT_DIR="${AGENT_DIR}"/"${AGENCY_AGENT_REPO}"

TMP_OUT_ROOT_DIR="${ROOT_DIR}"/out

OCI_REGISTRY="quay.io"
OCI_ORGANIZATION="rhivos-ai-tools"
PROJECT_NAME="claude-box"

SKILL_ARTIFACT_PREFIX="skill"
AGENT_ARTIFACT_PREFIX="agent"

clean() {
    echo "Removing temporary artifacts..."
    rm -rf "${TMP_OUT_ROOT_DIR}"
}

claude() {
    podman build \
        -f "${ROOT_DIR}"/containers/Containerfile \
        -t "${OCI_REGISTRY}/${OCI_ORGANIZATION}/${PROJECT_NAME}:latest" \
        "${ROOT_DIR}"
}

list_available_skills() {
    for dir in "${ANTHROPIC_SKILLS_DIR}"/*; do
        name=$(basename "${dir}")
        echo "${ANTHROPIC_SKILLS_REPO}/${name}"
    done

    for dir in "${OBRA_SKILLS_DIR}"/*; do
        name=$(basename "${dir}")
        echo "${OBRA_SKILLS_REPO}/${name}"
    done
}

list_available_oci_skills() {
    local artifacts=$(podman artifact ls --format "{{.Repository}}:{{.Tag}}" | grep "${OCI_REGISTRY}/${OCI_ORGANIZATION}/")
    for artifact in $artifacts; do
        if [[ "${artifact}" == "${OCI_REGISTRY}/${OCI_ORGANIZATION}/${SKILL_ARTIFACT_PREFIX}"* ]]; then
            echo $artifact
        fi
    done
}

remove_skills() {
    REMOVE_SKILLS_USAGE=$(cat <<'EOF'
Remove OCI artifacts for skills. By default, OCI artifacts for all
available skills are removed.

Usage:
    claude-box-builder skills remove [options]

Flags:
    --name      Remove only the skill identified by name
    -h, --help  Print help
EOF
)
    NAME="*"
    while [[ $# -gt 0 ]]; do
        case $1 in
            --name)
                shift
                NAME="${1}"
                shift
                ;;
            -h|--help)
                echo "$REMOVE_SKILLS_USAGE"
                exit 0
                ;;
            -*|--*)
                echo "Unknown option $1"
                echo "$REMOVE_SKILLS_USAGE"
                exit 1
                ;;
            *)
                echo "Unknown positional argument: $1"
                echo "$REMOVE_SKILLS_USAGE"
                exit 1
                ;;
        esac
    done

    mapfile -t available_oci_skills < <(list_available_oci_skills)
    for oci_skill in "${available_oci_skills[@]}"; do
        if [[ "${oci_skill}" == $NAME ]]; then
            result=$(podman artifact rm "${oci_skill}")
            echo "Removed ${oci_skill} (${result})"
        fi
    done
}

build_skills() {
    BUILD_SKILLS_USAGE=$(cat <<'EOF'
Build OCI artifacts for skills. By default, OCI artifacts for all
available skills are built.

Usage:
    claude-box-builder skills build [options]

Flags:
    --name      Build only the skill identified by name
    -h, --help  Print help
EOF
)
    NAME="*"
    while [[ $# -gt 0 ]]; do
        case $1 in
            --name)
                shift
                NAME="${1}"
                shift
                ;;
            -h|--help)
                echo "$BUILD_SKILLS_USAGE"
                exit 0
                ;;
            -*|--*)
                echo "Unknown option $1"
                echo "$BUILD_SKILLS_USAGE"
                exit 1
                ;;
            *)
                echo "Unknown positional argument: $1"
                echo "$BUILD_SKILLS_USAGE"
                exit 1
                ;;
        esac
    done

    TMP_SKILL_OUT_DIR="${TMP_OUT_ROOT_DIR}/skills"
    mapfile -t available_skills < <(list_available_skills)
    for skill in "${available_skills[@]}"; do
        if [[ "${skill}" == $NAME ]]; then

            SKILL_DIR=""
            if [[ "${skill}" == "${ANTHROPIC_SKILLS_REPO}"/* ]]; then
                SKILL_DIR="${ANTHROPIC_SKILLS_DIR}"
            elif [[ "${skill}" == "${OBRA_SKILLS_REPO}"/* ]]; then
                SKILL_DIR="${OBRA_SKILLS_DIR}"
            else
                echo "Unknown skill '${skill}'"
                exit 1
            fi
            SKILL_NAME=$(basename "${skill}")
            ARTIFACT_NAME="${OCI_REGISTRY}/${OCI_ORGANIZATION}/${SKILL_ARTIFACT_PREFIX}-${SKILL_NAME}":latest
            TMP_OUT_DIR="${TMP_SKILL_OUT_DIR}/${SKILL_NAME}"
            TMP_OUT_FILE="${TMP_OUT_DIR}/${SKILL_NAME}.tar"

            mkdir -p "${TMP_OUT_DIR}"
            pushd "${SKILL_DIR}"
            tar -cf "${TMP_OUT_FILE}" "${SKILL_NAME}" | \
                podman artifact add \
                --replace "${ARTIFACT_NAME}" \
                "${TMP_OUT_FILE}"
            popd
            SKILL_VERSION=$(git -C "${SKILL_DIR}" rev-parse HEAD)
            SKILL_URL=$(git -C "${SKILL_DIR}" config --get remote.origin.url)
            echo "url: ${SKILL_URL}" > "${TMP_OUT_DIR}/skill-meta.info"
            echo "version: ${SKILL_VERSION}" >> "${TMP_OUT_DIR}/skill-meta.info"
            podman artifact add \
                --append "${ARTIFACT_NAME}" \
                "${TMP_OUT_DIR}/skill-meta.info"
        fi
    done
}

skills(){
    SKILLS_USAGE=$(cat <<'EOF'
Operations for skills

Usage:
    claude-box-builder skills [commands]
    claude-box-builder skills [options]

Available commands:
    ls          List all available skills
    oci-ls      List locally available OCI skill artifacts
    build       Build OCI artifacts for the selected skills
    remove      Remove OCI artifacts for the selected skills

Flags:
    -h, --help  Print help
EOF
)

    COMMAND=""
    case $1 in
        ls)
            COMMAND=list_available_skills
            shift
            ;;
        oci-ls)
            COMMAND=list_available_oci_skills
            shift
            ;;
        build)
            COMMAND=build_skills
            shift
            ;;
        remove)
            COMMAND=remove_skills
            shift
            ;;
        -h|--help)
            echo "${SKILLS_USAGE}"
            exit 0
            ;;
        *)
            echo "Unknown positional argument: $1"
            echo "${SKILLS_USAGE}"
            exit 1
            ;;
    esac

    $COMMAND "$@"
}


list_available_agents() {
    for dir in "${AGENCY_AGENT_DIR}"/*; do

        if [[ -d "${dir}" ]]; then
            category=$(basename "${dir}")
            echo "${AGENCY_AGENT_REPO}/${category}"
            for subdir in "${dir}"/*; do
                name=$(basename "${subdir}")
                echo "   - ${name}"
            done
        else
            name=$(basename "${dir}")
            echo "${AGENCY_AGENT_REPO}"
            echo "   - ${name}"
        fi
    done
}

list_available_agent_category() {
    for dir in "${AGENCY_AGENT_DIR}"/*; do
        agent=$(basename "${dir}")

        provider_path=$(realpath "${dir}/..")
        provider=$(basename "${provider_path}")

        echo "${provider}/${agent}"
    done
}

list_available_oci_agents() {
    local artifacts=$(podman artifact ls --format "{{.Repository}}:{{.Tag}}" | grep "${OCI_REGISTRY}/${OCI_ORGANIZATION}/")
    
    for artifact in $artifacts; do
        if [[ "${artifact}" == "${OCI_REGISTRY}/${OCI_ORGANIZATION}/${AGENT_ARTIFACT_PREFIX}"* ]]; then
            echo $artifact
        fi
    done
}

remove_agents() {
    REMOVE_SKILLS_USAGE=$(cat <<'EOF'
Remove OCI artifacts for agents. By default, OCI artifacts for all
available agents are removed.

Usage:
    claude-box-builder agents remove [options]

Flags:
    --category      Remove only the agent identified by category.
    -h, --help      Print help
EOF
)
    CATEGORY="*"
    while [[ $# -gt 0 ]]; do
        case $1 in
            --category)
                shift
                CATEGORY="${1}"
                shift
                ;;
            -h|--help)
                echo "$REMOVE_SKILLS_USAGE"
                exit 0
                ;;
            -*|--*)
                echo "Unknown option $1"
                echo "$REMOVE_SKILLS_USAGE"
                exit 1
                ;;
            *)
                echo "Unknown positional argument: $1"
                echo "$REMOVE_SKILLS_USAGE"
                exit 1
                ;;
        esac
    done

    mapfile -t available_oci_agents < <(list_available_oci_agents)
    for oci_agent in "${available_oci_agents[@]}"; do
        if [[ "${oci_agent}" == $CATEGORY ]]; then
            result=$(podman artifact rm "${oci_agent}")
            echo "Removed ${oci_agent} (${result})"
        fi
    done
}

build_agents() {
    BUILD_AGENT_USAGE=$(cat <<'EOF'
Build OCI artifacts for agents. By default, OCI artifacts for all
available agents are built.

Usage:
    claude-box-builder agents build [options]

Flags:
    --category      Build only the agent identified by category in the form of <provider>/<category>.
    -h, --help      Print help
EOF
)
    CATEGORY="*"
    while [[ $# -gt 0 ]]; do
        case $1 in
            --category)
                shift
                CATEGORY="${1}"
                shift
                ;;
            -h|--help)
                echo "$BUILD_AGENT_USAGE"
                exit 0
                ;;
            -*|--*)
                echo "Unknown option $1"
                echo "$BUILD_AGENT_USAGE"
                exit 1
                ;;
            *)
                echo "Unknown positional argument: $1"
                echo "$BUILD_AGENT_USAGE"
                exit 1
                ;;
        esac
    done

    TMP_AGENT_OUT_DIR="${TMP_OUT_ROOT_DIR}/agents"
    mapfile -t available_agent_categories < <(list_available_agent_category)
    for agent_category in "${available_agent_categories[@]}"; do
        if [[ "${agent_category}" == $CATEGORY ]]; then

            CATEGORY_NAME=$(basename "${agent_category}")

            PROVIDER_DIR=$(realpath "${AGENT_DIR}/${agent_category}/..")

            ARTIFACT_NAME="${OCI_REGISTRY}/${OCI_ORGANIZATION}/${AGENT_ARTIFACT_PREFIX}-${CATEGORY_NAME}":latest
            TMP_OUT_DIR="${TMP_AGENT_OUT_DIR}/${CATEGORY_NAME}"
            TMP_OUT_FILE="${TMP_OUT_DIR}/${CATEGORY_NAME}.tar"

            mkdir -p "${TMP_OUT_DIR}"
            pushd "${PROVIDER_DIR}"
            tar -cf "${TMP_OUT_FILE}" "${CATEGORY_NAME}" | \
                podman artifact add \
                --replace "${ARTIFACT_NAME}" \
                "${TMP_OUT_FILE}"
            popd

            GIT_DIR=$(dirname "${AGENT_DIR}/${agent}")
            AGENT_VERSION=$(git -C "${GIT_DIR}" rev-parse HEAD)
            AGENT_URL=$(git -C "${GIT_DIR}" config --get remote.origin.url)
            echo "url: ${AGENT_URL}" > "${TMP_OUT_DIR}/agent-meta.info"
            echo "version: ${AGENT_VERSION}" >> "${TMP_OUT_DIR}/agent-meta.info"
            podman artifact add \
                --append "${ARTIFACT_NAME}" \
                "${TMP_OUT_DIR}/agent-meta.info"
        fi
    done
}

agents(){
    AGENTS_USAGE=$(cat <<'EOF'
Operations for agents

Usage:
    claude-box-builder agents [commands]
    claude-box-builder agents [options]

Available commands:
    ls          List all available agents
    oci-ls      List locally available OCI agent artifacts
    build       Build OCI artifacts for the selected agents
    remove      Remove OCI artifacts for the selected agents

Flags:
    -h, --help  Print help
EOF
)

    COMMAND=""
    case $1 in
        ls)
            COMMAND=list_available_agents
            shift
            ;;
        oci-ls)
            COMMAND=list_available_oci_agents
            shift
            ;;
        build)
            COMMAND=build_agents
            shift
            ;;
        remove)
            COMMAND=remove_agents
            shift
            ;;
        -h|--help)
            echo "${AGENTS_USAGE}"
            exit 0
            ;;
        *)
            echo "Unknown positional argument: $1"
            echo "${AGENTS_USAGE}"
            exit 1
            ;;
    esac

    $COMMAND "$@"
}

BASIC_USAGE=$(cat <<'EOF'
CLI to build OCI artifacts for skills and agents

Usage:
    claude-box-builder [command]

Available commands:
    skills      Build OCI artifacts for skills
    agents      Build OCI artifacts for agents
    clean       Remove all temporary files

Flags:
    -h, --help  Print help
EOF
)

COMMAND=""
case $1 in
    claude)
        COMMAND=claude
        shift
        ;;
    skills)
        COMMAND=skills
        shift
        ;;
    agents)
        COMMAND=agents
        shift
        ;;
    clean)
        COMMAND=clean
        shift
        ;;
    -h|--help)
        echo "${BASIC_USAGE}"
        exit 0
        ;;
    *)
        echo "Unknown positional argument: $1"
        echo "${BASIC_USAGE}"
        exit 1
        ;;
esac

$COMMAND "$@"
