name: Publish

on:
  push:
    tags:
      - 'v*.*.*'

jobs:

  pypipublish:
    name: Publish aicrate on PyPi
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt upgrade -y
          sudo apt install python3 python3-pip python3-build python3-venv -y

      - name: Build python package
        run: |
          ./scripts/package.sh --wheel

      - name: Publish aicrate to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          packages-dir: out/pypi/
